import { test, expect } from '@playwright/test'
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import http from 'node:http'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { unzipSync, strFromU8 } from 'fflate'
import { mockPublicConfig, setupUser } from './helpers'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')

function runNeuDrive(args: string[]) {
  const configured = process.env.NEUDRIVE_CLI
  if (configured) {
    execFileSync(configured, args, { stdio: 'inherit' })
    return
  }
  if (fs.existsSync('/tmp/neudrive')) {
    execFileSync('/tmp/neudrive', args, { stdio: 'inherit' })
    return
  }
  execFileSync('go', ['run', './cmd/neudrive', ...args], { cwd: ROOT, stdio: 'inherit' })
}

async function expectAPISuccess(response: any) {
  const body = await response.json()
  expect(response.ok(), JSON.stringify(body)).toBeTruthy()
  return body.data
}

async function createSyncToken(request: any, userToken: string, access: 'push' | 'pull' | 'both' = 'both') {
  const data = await expectAPISuccess(await request.post('/api/tokens/sync', {
    headers: { Authorization: `Bearer ${userToken}` },
    data: { access, ttl_minutes: 30 },
  }))
  return data.token as string
}

function writeSkillSourceDir(skillName: string) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), `pw-sync-src-${Date.now()}`))
  const skillRoot = path.join(root, skillName)
  fs.mkdirSync(path.join(skillRoot, 'references'), { recursive: true })
  fs.writeFileSync(path.join(skillRoot, 'SKILL.md'), `# ${skillName}\nGenerated by Playwright`, 'utf8')
  fs.writeFileSync(path.join(skillRoot, 'references', 'notes.md'), 'archive fixture content', 'utf8')
  return root
}

test.describe('Bundle Sync', () => {
  test('cli login flow can send token back to localhost callback', async ({ page, request }) => {
    await setupUser(page, request)

    const callback = await new Promise<{ url: string; received: Promise<any>; close: () => Promise<void> }>((resolve) => {
      let resolver = (_payload: any) => {}
      const received = new Promise<any>((innerResolve) => {
        resolver = innerResolve
      })
      const server = http.createServer((req, res) => {
        res.setHeader('Access-Control-Allow-Origin', '*')
        res.setHeader('Access-Control-Allow-Headers', 'Content-Type')
        if (req.method === 'OPTIONS') {
          res.statusCode = 204
          res.end()
          return
        }
        if (req.method !== 'POST' || req.url !== '/callback') {
          res.statusCode = 404
          res.end()
          return
        }
        const chunks: Buffer[] = []
        req.on('data', (chunk) => chunks.push(Buffer.from(chunk)))
        req.on('end', () => {
          res.setHeader('Content-Type', 'application/json')
          res.end(JSON.stringify({ ok: true }))
          resolver(JSON.parse(Buffer.concat(chunks).toString('utf8')))
        })
      })
      server.listen(0, '127.0.0.1', () => {
        const address = server.address()
        if (!address || typeof address === 'string') {
          throw new Error('failed to start callback server')
        }
        resolve({
          url: `http://127.0.0.1:${address.port}/callback`,
          received,
          close: () => new Promise<void>((innerResolve, innerReject) => server.close((err) => err ? innerReject(err) : innerResolve())),
        })
      })
    })

    try {
      const params = new URLSearchParams({
        cli_login: '1',
        cli_profile: 'prod',
        cli_access: 'both',
        cli_ttl_minutes: '30',
        cli_callback: callback.url,
        cli_state: 'pw-sync-state',
      })
      await page.goto(`/sync/login?${params.toString()}`)
      await expect(page.getByRole('heading', { name: /授权本次 Sync 登录|Authorize this Sync sign-in/ })).toBeVisible()
      await page.getByRole('button', { name: /继续并授权 CLI|Continue and authorize CLI/ }).click()
      await expect(page.getByText(/已把 Sync Token 发回本地 CLI profile：prod|The Sync token was sent back to local CLI profile prod/)).toBeVisible({ timeout: 15000 })
      const payload = await callback.received
      expect(payload.state).toBe('pw-sync-state')
      expect(payload.profile).toBe('prod')
      expect(payload.token.startsWith('ndt_')).toBeTruthy()
      expect(payload.api_base).toMatch(/^http/)
    } finally {
      await callback.close()
    }
  })

  test('legacy sync route redirects according to public config', async ({ page, request }) => {
    await mockPublicConfig(page, {
      git_mirror_execution_mode: 'local',
      github_app_enabled: false,
      local_mode: true,
    })
    await page.route('**/api/git-mirror', async (route) => {
      if (route.request().method() !== 'GET') {
        await route.fallback()
        return
      }
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          ok: true,
          data: {
            enabled: true,
            execution_mode: 'local',
            sync_state: 'idle',
            auto_commit_enabled: true,
            auto_push_enabled: true,
            auth_mode: 'local_credentials',
            remote_name: 'origin',
            remote_branch: 'main',
            github_token_configured: false,
            github_app_user_connected: false,
          },
        }),
      })
    })
    await setupUser(page, request)

    await page.goto('/data/sync')
    await page.waitForURL(/\/sync-backup$/, { timeout: 15000 })
    await expect(page.getByRole('heading', { name: 'Backup destination' })).toBeVisible()
    await expect(page.locator('#git-mirror-auth-mode')).toBeVisible()
    await expect(page.locator('#git-mirror-auth-mode option[value="local_credentials"]')).toHaveCount(1)
    await expect(page.locator('#git-mirror-auth-mode option[value="github_token"]')).toHaveCount(1)
    await expect(page.locator('#git-mirror-auth-mode option[value="github_app_user"]')).toHaveCount(1)
    await page.locator('#git-mirror-auth-mode').selectOption('github_app_user')
    await expect(page.getByText(/当前服务没有配置 GitHub App 授权|GitHub App authorization is not configured/)).toBeVisible()
  })

  test('hosted GitHub Backup hides advanced auth and sync internals', async ({ page, request }) => {
    await mockPublicConfig(page, {
      git_mirror_execution_mode: 'hosted',
      github_app_enabled: true,
      github_app_slug: 'neudrive',
      local_mode: false,
    })
    await page.route('**/api/git-mirror', async (route) => {
      if (route.request().method() !== 'GET') {
        await route.fallback()
        return
      }
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          ok: true,
          data: {
            enabled: true,
            execution_mode: 'hosted',
            sync_state: 'idle',
            auto_commit_enabled: true,
            auto_push_enabled: true,
            auth_mode: 'github_app_user',
            remote_name: 'origin',
            remote_url: 'https://github.com/octocat/neudrive-backup.git',
            remote_branch: 'main',
            last_push_at: '2026-05-07T12:00:00Z',
            github_token_configured: false,
            github_app_user_connected: true,
            github_app_user_login: 'octocat',
          },
        }),
      })
    })
    await setupUser(page, request)

    await page.goto('/sync-backup')
    await expect(page.getByRole('heading', { name: 'Backup destination' })).toBeVisible()
    await expect(page.getByText(/最近更新时间|Last update/)).toBeVisible()
    await expect(page.getByText('octocat/neudrive-backup')).toHaveCount(0)
    await expect(page.getByRole('button', { name: /立即同步|Sync now/ })).toBeVisible()
    await expect(page.getByText(/Execution mode|Sync state|Attempt count|Auto commit|Auto push|GitHub Token|Local Git credentials/)).toHaveCount(0)
  })

  test('preview mirror deletes with sync preview API', async ({ request, page }) => {
    const user = await setupUser(page, request)
    const syncToken = await createSyncToken(request, user.token, 'both')

    const initialBundle = {
      version: 'ahub.bundle/v1',
      created_at: new Date().toISOString(),
      source: 'playwright',
      mode: 'merge',
      profile: {},
      skills: {
        'pw-sync-skill': {
          files: {
            'SKILL.md': '# PW Sync Skill\nGenerated by Playwright',
            'references/notes.md': 'fixture content',
          },
          binary_files: {},
        },
      },
      memory: [],
      stats: {
        total_skills: 1,
        total_files: 2,
        total_bytes: 64,
        binary_files: 0,
        profile_items: 0,
        memory_items: 0,
      },
    }
    const mirrorBundle = {
      ...initialBundle,
      mode: 'mirror',
      skills: {
        'pw-sync-skill': {
          files: {
            'SKILL.md': '# PW Sync Skill\nGenerated by Playwright',
          },
          binary_files: {},
        },
      },
      stats: {
        total_skills: 1,
        total_files: 1,
        total_bytes: 32,
        binary_files: 0,
        profile_items: 0,
        memory_items: 0,
      },
    }

    const imported = await expectAPISuccess(await request.post('/agent/import/bundle', {
      headers: { Authorization: `Bearer ${syncToken}` },
      data: initialBundle,
    }))
    expect(imported.mode).toBe('merge')
    expect(imported.files_written).toBeGreaterThan(0)

    const preview = await expectAPISuccess(await request.post('/agent/import/preview', {
      headers: { Authorization: `Bearer ${syncToken}` },
      data: mirrorBundle,
    }))
    expect(preview.mode).toBe('mirror')
    expect(preview.fingerprint).toBeTruthy()
    expect(preview.summary.delete).toBeGreaterThan(0)
    expect(preview.skills['pw-sync-skill']).toBeTruthy()
    expect(preview.skills['pw-sync-skill'].files).toEqual(expect.arrayContaining([
      expect.objectContaining({
        path: '/skills/pw-sync-skill/references/notes.md',
        action: 'delete',
      }),
    ]))
  })

  test('archive sync session can be resumed and committed through API', async ({ page, request }) => {
    const user = await setupUser(page, request)
    const sourceDir = writeSkillSourceDir('pw-archive-skill')
    const archivePath = path.join(os.tmpdir(), `pw-sync-${Date.now()}.ndrvz`)
    const syncToken = await createSyncToken(request, user.token, 'both')

    runNeuDrive(['sync', 'export', '--source', sourceDir, '--format', 'archive', '-o', archivePath])

    const archiveBytes = fs.readFileSync(archivePath)
    const manifestFiles = unzipSync(new Uint8Array(archiveBytes))
    const manifest = JSON.parse(strFromU8(manifestFiles['manifest.json']))

    const startRes = await request.post('/agent/import/session', {
      headers: {
        Authorization: `Bearer ${syncToken}`,
      },
      data: {
        transport_version: 'ahub.sync/v1',
        format: 'archive',
        mode: 'merge',
        manifest,
        archive_size_bytes: archiveBytes.length,
        archive_sha256: manifest.archive_sha256,
      },
    })
    const started = await expectAPISuccess(startRes)
    expect(started.session_id).toBeTruthy()
    expect(started.total_parts).toBeGreaterThan(0)

    try {
      const uploading = await expectAPISuccess(await request.get(`/agent/import/session/${started.session_id}`, {
        headers: { Authorization: `Bearer ${syncToken}` },
      }))
      expect(uploading.status).toBe('uploading')

      const chunkSize = Number(started.chunk_size_bytes)
      for (let index = 0; index < started.total_parts; index += 1) {
        const start = index * chunkSize
        const end = Math.min(start + chunkSize, archiveBytes.length)
        const uploaded = await expectAPISuccess(await request.put(`/agent/import/session/${started.session_id}/parts/${index}`, {
          headers: {
            Authorization: `Bearer ${syncToken}`,
            'Content-Type': 'application/octet-stream',
          },
          data: archiveBytes.subarray(start, end),
        }))
        expect(uploaded.session_id).toBe(started.session_id)
      }

      const ready = await expectAPISuccess(await request.get(`/agent/import/session/${started.session_id}`, {
        headers: { Authorization: `Bearer ${syncToken}` },
      }))
      expect(ready.status).toBe('ready')

      const preview = await expectAPISuccess(await request.post('/agent/import/preview', {
        headers: { Authorization: `Bearer ${syncToken}` },
        data: { manifest },
      }))
      expect(preview.fingerprint).toBeTruthy()

      const committed = await expectAPISuccess(await request.post(`/agent/import/session/${started.session_id}/commit`, {
        headers: { Authorization: `Bearer ${syncToken}` },
        data: {},
      }))
      expect(committed.files_written).toBeGreaterThan(0)

      const session = await expectAPISuccess(await request.get(`/agent/import/session/${started.session_id}`, {
        headers: { Authorization: `Bearer ${syncToken}` },
      }))
      expect(session.status).toBe('committed')

      const importedSkill = await expectAPISuccess(await request.get('/api/tree/skills/pw-archive-skill/SKILL.md', {
        headers: { Authorization: `Bearer ${user.token}` },
      }))
      expect(importedSkill.content).toContain('pw-archive-skill')
    } finally {
      fs.rmSync(sourceDir, { recursive: true, force: true })
      fs.unlinkSync(archivePath)
    }
  })
})
